# ============================================================
#  application-dev.properties — configuration locale (Docker)
# ============================================================

# ── Base de données locale (Docker) ──────────────────────────
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.cyfupratwjkaynqnbwar
spring.datasource.password=projetdevops
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=dev_secret_key_collabyouth_2025_change_in_prod
jwt.expiration=86400000

