server.port=8081

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.cyfupratwjkaynqnbwar
spring.datasource.password=projetdevops
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=681zYNMjzaXZvatepqqG7UkfyTe4-puIGRxSI0U9YB4
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=collabyouth20@gmail.com
spring.mail.password=bdukaoqcssiceapb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true